server:
    port: 8888
spring:
    cloud:
        config:
            server:
                #git:
                #   uri: file:///E:/gitrepo/spring-cloud-example/config-server-repo
                native:
                    searchLocations: E:/gitrepo/spring-cloud-example/config-server-repo

    profiles:
        active: native
